export const urlPermissions: {
  [key: string]: string;
} = {
  "/": "agent_stat",
  "/reports/supplier": "supplier_report",
  "/games/flyorder": "fly_config",
  "/games/odds": "edit_odds",
  "/games/ratio": "edit_radio",
  "/games/rebate": "edit_rebate",
  "/games/supplier": "supplier_config",
  "/games/maintain": "game_maintain",
  "/system/subaccount": "sub_account",
  "/system/role": "system_role",
  "/system/announcement/own": "own_announcement",
  "/system/announcement/all": "super_announcement",
  "/system/announcement/platform": "platform_announcement",
  "/maintain/dictionary": "dictionary",
  "/maintain/resource": "resource_config",
  "/fund/withdrawfee": "withdrawfee",
  "/fund/minerfee": "minerfee",
  "/fund/collection": "collection",
  "/withdraw/apply": "withdraw_apply",
  "/withdraw/audit": "audit",
  "/users/supplier": "users_supplier",
  "/personal/security": "edit_password",
  "/personal/info": "personal_info",
  "/personal/loginlog": "login_log",
  "/users/agent": "agent_config",
  "/users/member": "member_config",
};
