export const urlPermissions: {
  [key: string]: string;
} = {
  "/": "agent_stat",
  "/reports/supplier": "supplier_report",
  "/games/flyorder": "fly_config",
  "/games/odds": "edit_odds",
  "/games/ratio": "edit_radio",
  "/games/rebate": "edit_rebate",
  "/games/supplier": "supplier_config",
  "/games/maintain": "game_maintain",
  "/system/subaccount": "sub_account",
  "/system/role": "system_role",
  "/system/announcement/own": "own_announcement",
  "/system/announcement/all": "super_announcement",
  "/system/announcement/platform": "platform_announcement",
  "/maintain/dictionary": "dictionary",
  "/maintain/resource": "resource_config",
  "/fund/withdrawfee": "withdrawfee",
  "/fund/minerfee": "minerfee",
  "/fund/collection": "collection",
  "/withdraw/apply": "withdraw_apply",
  "/withdraw/audit": "audit",
  "/users/supplier": "users_supplier",
  "/personal/security": "edit_password",
  "/personal/info": "personal_info",
  "/personal/loginlog": "login_log",
  "/users/agent": "agent_config",
  "/users/member": "member_config",
  "/reports/agent/guandan": "agent_report_guandan",
  "/reports/agent/baccarat": "agent_report_baccarat",
  "/reports/order/guandan": "detail_guandan",
  "/reports/order/baccarat": "detail_baccarat",
  "/reports/period": "period_report",
  "/reports/member/baccarat": "member_report_baccarat",
  "/reports/change": "change_report",
  "/reports/recharge": "recharge_report",
  "/reports/withdraw": "withdraw_report",
  "/reports/borrow": "borrow_report",
  "/reports/reward": "reward_report",
  "/reports/credit": "credit_report",
  "/reports/transfer": "transfer_report",
  "/reports/download": "report_download",
};
