admin-build:
  stage: build
  tags:
    - build
  only:
    - test
  script:
    - cd admin
    - docker build -t 172.31.46.150:5555/admin-006:$CI_COMMIT_SHORT_SHA .
    - docker push 172.31.46.150:5555/admin-006:$CI_COMMIT_SHORT_SHA

landing-build:
  stage: build
  tags:
    - build
  only:
    - test
  script:
    - cd landing
    - docker build -t 172.31.46.150:5555/landing-006:$CI_COMMIT_SHORT_SHA .
    - docker push 172.31.46.150:5555/landing-006:$CI_COMMIT_SHORT_SHA

admin-deploy:
  stage: deploy
  tags:
    - deploy
  only:
    - test
  dependencies:
    - admin-build
  script:
    - docker pull 18.163.249.24:5555/admin-006:$CI_COMMIT_SHORT_SHA
    - docker stop admin-006 || true
    - docker rm admin-006 || true
    - docker run -d -p 3333:3000 --name admin-006 --network demo --restart unless-stopped 18.163.249.24:5555/admin-006:$CI_COMMIT_SHORT_SHA

landing-deploy:
  stage: deploy
  tags:
    - deploy
  only:
    - test
  dependencies:
    - landing-build
  script:
    - docker pull 18.163.249.24:5555/landing-006:$CI_COMMIT_SHORT_SHA
    - docker stop landing-006 || true
    - docker rm landing-006 || true
    - docker run -d -p 3334:80 --name landing-006 --network demo --restart unless-stopped 18.163.249.24:5555/landing-006:$CI_COMMIT_SHORT_SHA