http {
    upstream backend {
        least_conn;
#        server demo1:3000;  # 指定第一个后端容器，注意容器名和端口
        server admin-006:3000;  # 指定第二个后端容器
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;  # 将请求转发到后端
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
	        proxy_set_header X-Forwarded-Host $host;
            proxy_set_header Origin $http_origin;
        }
    }
}
events {
    worker_connections 1024;
}